#!/usr/bin/env python3
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
"""
Generate src/openjd/model/_version.py from the git VCS state.

The openjd-model-for-python build backend is maturin, which does not
run hatchling build hooks. This means the `[tool.hatch.build.hooks.vcs]`
mechanism that normally populates `_version.py` does nothing here.

This script produces the same file independently, using setuptools_scm
(which is what hatch-vcs wraps) with the `post-release` version scheme
configured in pyproject.toml's `[tool.hatch.version.raw-options]`.

It's invoked by `hatch.toml`'s `pre-install-commands` so that
`maturin develop` sees an up-to-date `_version.py` before building.

Run directly:
    python scripts/generate_version.py

The output file is gitignored and must not be committed.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATH = REPO_ROOT / "src" / "openjd" / "model" / "_version.py"

TEMPLATE = """\
# file generated by vcs-versioning
# don't change, don't track in version control
from __future__ import annotations

__all__ = [
    "__version__",
    "__version_tuple__",
    "version",
    "version_tuple",
    "__commit_id__",
    "commit_id",
]

version: str
__version__: str
__version_tuple__: tuple[int | str, ...]
version_tuple: tuple[int | str, ...]
commit_id: str | None
__commit_id__: str | None

__version__ = version = {version!r}
__version_tuple__ = version_tuple = {version_tuple!r}

__commit_id__ = commit_id = None
"""


def _parse_version_tuple(version: str) -> tuple:
    """Convert a PEP 440 version string into the tuple form that hatch-vcs emits.

    Examples:
        '0.9.1.post7+g5e10e2c03' -> (0, 9, 1, 'post7', 'g5e10e2c03')
        '0.9.1'                  -> (0, 9, 1)
        '0.9.1.post7'            -> (0, 9, 1, 'post7')
    """
    local = None
    if "+" in version:
        base, local = version.split("+", 1)
    else:
        base = version

    # Split the base into numeric segments and one optional post-release segment.
    # PEP 440 allows postN to appear after the numeric release segments.
    m = re.match(r"^(\d+(?:\.\d+)*)(?:\.(post\d+))?$", base)
    if not m:
        # Fall back to a trivial decomposition.
        parts: tuple = tuple(
            int(p) if p.isdigit() else p for p in base.replace("+", ".").split(".")
        )
        return parts

    numeric, post = m.group(1), m.group(2)
    parts = tuple(int(p) for p in numeric.split("."))
    if post is not None:
        parts = parts + (post,)
    if local is not None:
        parts = parts + (local,)
    return parts


def compute_version() -> str:
    try:
        import setuptools_scm
    except ImportError:  # pragma: no cover
        sys.stderr.write(
            "ERROR: setuptools_scm is required to generate _version.py.\n"
            "Install it into the build environment (e.g. `pip install setuptools_scm`).\n"
        )
        sys.exit(1)

    # Match the settings in pyproject.toml's [tool.hatch.version] /
    # [tool.hatch.version.raw-options] so the produced string is identical
    # to what hatch-vcs would have produced.
    return setuptools_scm.get_version(
        root=str(REPO_ROOT),
        version_scheme="post-release",
        # Default local_scheme is "node-and-date", but hatch-vcs historically
        # produced "+g<shorthash>" without a date. That corresponds to
        # setuptools_scm's `node-and-timestamp` behavior being suppressed
        # because the working tree is clean. To match the observed format
        # exactly, force the node-only local scheme.
        local_scheme="node-and-date",
    )


def write_version_file(version: str) -> bool:
    """Write _version.py for the given version string. Returns True if changed."""
    version_tuple = _parse_version_tuple(version)
    content = TEMPLATE.format(version=version, version_tuple=version_tuple)

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)

    if OUTPUT_PATH.exists() and OUTPUT_PATH.read_text() == content:
        # Idempotent no-op: leave mtime alone so we don't defeat build caches.
        return False

    OUTPUT_PATH.write_text(content)
    return True


def main() -> int:
    version = compute_version()
    if write_version_file(version):
        print(f"Wrote {OUTPUT_PATH.relative_to(REPO_ROOT)} (version {version})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
